//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace klient_do_WCF.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataContractIService1WelcomeHistory", Namespace="http://schemas.datacontract.org/2004/07/Wcfsimplelibrary")]
    [System.SerializableAttribute()]
    public partial class DataContractIService1WelcomeHistory : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AgentActionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AgentAction {
            get {
                return this.AgentActionField;
            }
            set {
                if ((this.AgentActionField.Equals(value) != true)) {
                    this.AgentActionField = value;
                    this.RaisePropertyChanged("AgentAction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Author {
            get {
                return this.AuthorField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorField, value) != true)) {
                    this.AuthorField = value;
                    this.RaisePropertyChanged("Author");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataContractIService1SendOrder", Namespace="http://schemas.datacontract.org/2004/07/Wcfsimplelibrary")]
    [System.SerializableAttribute()]
    public partial class DataContractIService1SendOrder : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdressinfomationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailclientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool FinishorderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OptionsendField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adressinfomation {
            get {
                return this.AdressinfomationField;
            }
            set {
                if ((object.ReferenceEquals(this.AdressinfomationField, value) != true)) {
                    this.AdressinfomationField = value;
                    this.RaisePropertyChanged("Adressinfomation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Clientname {
            get {
                return this.ClientnameField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientnameField, value) != true)) {
                    this.ClientnameField = value;
                    this.RaisePropertyChanged("Clientname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Emailclient {
            get {
                return this.EmailclientField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailclientField, value) != true)) {
                    this.EmailclientField = value;
                    this.RaisePropertyChanged("Emailclient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Finishorder {
            get {
                return this.FinishorderField;
            }
            set {
                if ((this.FinishorderField.Equals(value) != true)) {
                    this.FinishorderField = value;
                    this.RaisePropertyChanged("Finishorder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Itemname {
            get {
                return this.ItemnameField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemnameField, value) != true)) {
                    this.ItemnameField = value;
                    this.RaisePropertyChanged("Itemname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Optionsend {
            get {
                return this.OptionsendField;
            }
            set {
                if ((object.ReferenceEquals(this.OptionsendField, value) != true)) {
                    this.OptionsendField = value;
                    this.RaisePropertyChanged("Optionsend");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/WelcomeHistory", ReplyAction="http://tempuri.org/IService1/WelcomeHistoryResponse")]
        string WelcomeHistory(klient_do_WCF.ServiceReference1.DataContractIService1WelcomeHistory ALL);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/WelcomeHistory", ReplyAction="http://tempuri.org/IService1/WelcomeHistoryResponse")]
        System.IAsyncResult BeginWelcomeHistory(klient_do_WCF.ServiceReference1.DataContractIService1WelcomeHistory ALL, System.AsyncCallback callback, object asyncState);
        
        string EndWelcomeHistory(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DateReturn", ReplyAction="http://tempuri.org/IService1/DateReturnResponse")]
        string DateReturn();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/DateReturn", ReplyAction="http://tempuri.org/IService1/DateReturnResponse")]
        System.IAsyncResult BeginDateReturn(System.AsyncCallback callback, object asyncState);
        
        string EndDateReturn(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SendOrder", ReplyAction="http://tempuri.org/IService1/SendOrderResponse")]
        string SendOrder(klient_do_WCF.ServiceReference1.DataContractIService1SendOrder data);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/SendOrder", ReplyAction="http://tempuri.org/IService1/SendOrderResponse")]
        System.IAsyncResult BeginSendOrder(klient_do_WCF.ServiceReference1.DataContractIService1SendOrder data, System.AsyncCallback callback, object asyncState);
        
        string EndSendOrder(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ReadText", ReplyAction="http://tempuri.org/IService1/ReadTextResponse")]
        string ReadText();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/ReadText", ReplyAction="http://tempuri.org/IService1/ReadTextResponse")]
        System.IAsyncResult BeginReadText(System.AsyncCallback callback, object asyncState);
        
        string EndReadText(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : klient_do_WCF.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WelcomeHistoryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public WelcomeHistoryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DateReturnCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public DateReturnCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SendOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SendOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReadTextCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ReadTextCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<klient_do_WCF.ServiceReference1.IService1>, klient_do_WCF.ServiceReference1.IService1 {
        
        private BeginOperationDelegate onBeginWelcomeHistoryDelegate;
        
        private EndOperationDelegate onEndWelcomeHistoryDelegate;
        
        private System.Threading.SendOrPostCallback onWelcomeHistoryCompletedDelegate;
        
        private BeginOperationDelegate onBeginDateReturnDelegate;
        
        private EndOperationDelegate onEndDateReturnDelegate;
        
        private System.Threading.SendOrPostCallback onDateReturnCompletedDelegate;
        
        private BeginOperationDelegate onBeginSendOrderDelegate;
        
        private EndOperationDelegate onEndSendOrderDelegate;
        
        private System.Threading.SendOrPostCallback onSendOrderCompletedDelegate;
        
        private BeginOperationDelegate onBeginReadTextDelegate;
        
        private EndOperationDelegate onEndReadTextDelegate;
        
        private System.Threading.SendOrPostCallback onReadTextCompletedDelegate;
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<WelcomeHistoryCompletedEventArgs> WelcomeHistoryCompleted;
        
        public event System.EventHandler<DateReturnCompletedEventArgs> DateReturnCompleted;
        
        public event System.EventHandler<SendOrderCompletedEventArgs> SendOrderCompleted;
        
        public event System.EventHandler<ReadTextCompletedEventArgs> ReadTextCompleted;
        
        public string WelcomeHistory(klient_do_WCF.ServiceReference1.DataContractIService1WelcomeHistory ALL) {
            return base.Channel.WelcomeHistory(ALL);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginWelcomeHistory(klient_do_WCF.ServiceReference1.DataContractIService1WelcomeHistory ALL, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginWelcomeHistory(ALL, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndWelcomeHistory(System.IAsyncResult result) {
            return base.Channel.EndWelcomeHistory(result);
        }
        
        private System.IAsyncResult OnBeginWelcomeHistory(object[] inValues, System.AsyncCallback callback, object asyncState) {
            klient_do_WCF.ServiceReference1.DataContractIService1WelcomeHistory ALL = ((klient_do_WCF.ServiceReference1.DataContractIService1WelcomeHistory)(inValues[0]));
            return this.BeginWelcomeHistory(ALL, callback, asyncState);
        }
        
        private object[] OnEndWelcomeHistory(System.IAsyncResult result) {
            string retVal = this.EndWelcomeHistory(result);
            return new object[] {
                    retVal};
        }
        
        private void OnWelcomeHistoryCompleted(object state) {
            if ((this.WelcomeHistoryCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.WelcomeHistoryCompleted(this, new WelcomeHistoryCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void WelcomeHistoryAsync(klient_do_WCF.ServiceReference1.DataContractIService1WelcomeHistory ALL) {
            this.WelcomeHistoryAsync(ALL, null);
        }
        
        public void WelcomeHistoryAsync(klient_do_WCF.ServiceReference1.DataContractIService1WelcomeHistory ALL, object userState) {
            if ((this.onBeginWelcomeHistoryDelegate == null)) {
                this.onBeginWelcomeHistoryDelegate = new BeginOperationDelegate(this.OnBeginWelcomeHistory);
            }
            if ((this.onEndWelcomeHistoryDelegate == null)) {
                this.onEndWelcomeHistoryDelegate = new EndOperationDelegate(this.OnEndWelcomeHistory);
            }
            if ((this.onWelcomeHistoryCompletedDelegate == null)) {
                this.onWelcomeHistoryCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnWelcomeHistoryCompleted);
            }
            base.InvokeAsync(this.onBeginWelcomeHistoryDelegate, new object[] {
                        ALL}, this.onEndWelcomeHistoryDelegate, this.onWelcomeHistoryCompletedDelegate, userState);
        }
        
        public string DateReturn() {
            return base.Channel.DateReturn();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginDateReturn(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDateReturn(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndDateReturn(System.IAsyncResult result) {
            return base.Channel.EndDateReturn(result);
        }
        
        private System.IAsyncResult OnBeginDateReturn(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginDateReturn(callback, asyncState);
        }
        
        private object[] OnEndDateReturn(System.IAsyncResult result) {
            string retVal = this.EndDateReturn(result);
            return new object[] {
                    retVal};
        }
        
        private void OnDateReturnCompleted(object state) {
            if ((this.DateReturnCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DateReturnCompleted(this, new DateReturnCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DateReturnAsync() {
            this.DateReturnAsync(null);
        }
        
        public void DateReturnAsync(object userState) {
            if ((this.onBeginDateReturnDelegate == null)) {
                this.onBeginDateReturnDelegate = new BeginOperationDelegate(this.OnBeginDateReturn);
            }
            if ((this.onEndDateReturnDelegate == null)) {
                this.onEndDateReturnDelegate = new EndOperationDelegate(this.OnEndDateReturn);
            }
            if ((this.onDateReturnCompletedDelegate == null)) {
                this.onDateReturnCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDateReturnCompleted);
            }
            base.InvokeAsync(this.onBeginDateReturnDelegate, null, this.onEndDateReturnDelegate, this.onDateReturnCompletedDelegate, userState);
        }
        
        public string SendOrder(klient_do_WCF.ServiceReference1.DataContractIService1SendOrder data) {
            return base.Channel.SendOrder(data);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginSendOrder(klient_do_WCF.ServiceReference1.DataContractIService1SendOrder data, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSendOrder(data, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndSendOrder(System.IAsyncResult result) {
            return base.Channel.EndSendOrder(result);
        }
        
        private System.IAsyncResult OnBeginSendOrder(object[] inValues, System.AsyncCallback callback, object asyncState) {
            klient_do_WCF.ServiceReference1.DataContractIService1SendOrder data = ((klient_do_WCF.ServiceReference1.DataContractIService1SendOrder)(inValues[0]));
            return this.BeginSendOrder(data, callback, asyncState);
        }
        
        private object[] OnEndSendOrder(System.IAsyncResult result) {
            string retVal = this.EndSendOrder(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSendOrderCompleted(object state) {
            if ((this.SendOrderCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SendOrderCompleted(this, new SendOrderCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SendOrderAsync(klient_do_WCF.ServiceReference1.DataContractIService1SendOrder data) {
            this.SendOrderAsync(data, null);
        }
        
        public void SendOrderAsync(klient_do_WCF.ServiceReference1.DataContractIService1SendOrder data, object userState) {
            if ((this.onBeginSendOrderDelegate == null)) {
                this.onBeginSendOrderDelegate = new BeginOperationDelegate(this.OnBeginSendOrder);
            }
            if ((this.onEndSendOrderDelegate == null)) {
                this.onEndSendOrderDelegate = new EndOperationDelegate(this.OnEndSendOrder);
            }
            if ((this.onSendOrderCompletedDelegate == null)) {
                this.onSendOrderCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSendOrderCompleted);
            }
            base.InvokeAsync(this.onBeginSendOrderDelegate, new object[] {
                        data}, this.onEndSendOrderDelegate, this.onSendOrderCompletedDelegate, userState);
        }
        
        public string ReadText() {
            return base.Channel.ReadText();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginReadText(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginReadText(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndReadText(System.IAsyncResult result) {
            return base.Channel.EndReadText(result);
        }
        
        private System.IAsyncResult OnBeginReadText(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginReadText(callback, asyncState);
        }
        
        private object[] OnEndReadText(System.IAsyncResult result) {
            string retVal = this.EndReadText(result);
            return new object[] {
                    retVal};
        }
        
        private void OnReadTextCompleted(object state) {
            if ((this.ReadTextCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ReadTextCompleted(this, new ReadTextCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ReadTextAsync() {
            this.ReadTextAsync(null);
        }
        
        public void ReadTextAsync(object userState) {
            if ((this.onBeginReadTextDelegate == null)) {
                this.onBeginReadTextDelegate = new BeginOperationDelegate(this.OnBeginReadText);
            }
            if ((this.onEndReadTextDelegate == null)) {
                this.onEndReadTextDelegate = new EndOperationDelegate(this.OnEndReadText);
            }
            if ((this.onReadTextCompletedDelegate == null)) {
                this.onReadTextCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnReadTextCompleted);
            }
            base.InvokeAsync(this.onBeginReadTextDelegate, null, this.onEndReadTextDelegate, this.onReadTextCompletedDelegate, userState);
        }
    }
}
